### ISSUE TITLE
How to input the dataset?

### ISSUE THREAD

**Issue by reachablesa** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#1]
Hi, 

What should be the format of files in "./data/faces/training/"?
I downloaded the AT&T dataset inside this folder but i still get the following error:

RuntimeError: invalid argument 1: must be strictly positive at /pytorch/torch/lib/TH/generic/THTensorMath.c:2033

it is because len(siamese_dataset)=0. It makes me think that I am not using the correct data file format.

**Comment by harveyslash** [comment]
Have you converted the images from pgm to png? The way to do it is mentioned in the Readme

**Comment by reachablesa** [comment]
When I converted, I got errors of the form:
IOError: [Errno 2] No such file or directory: 's9/2.pgm.png'

**Comment by harveyslash** [comment]
Thats probably the issue. 
Go to the directory where you downloaded the images, and give the output of : 
`find -name "*pgm"`

It should list out all the pgm files (I just tested , and it works).

**Comment by reachablesa** [comment]
This is what I got when I run that:
./s31/1.pgm
./s31/7.pgm
./s31/3.pgm
./s31/6.pgm
./s31/4.pgm
./s31/8.pgm
./s31/5.pgm
./s31/2.pgm

**Comment by harveyslash** [comment]
What OS are you on ?

**Comment by reachablesa** [comment]
Ubuntu 14.04

**Comment by harveyslash** [comment]
can you see if you have any png images generated at all? 
what is the output of `convert`

**Comment by reachablesa** [comment]
A png file is generated for each pgm file

**Comment by harveyslash** [comment]
do you have the right versions of pytorch and torch vision? 
And are you referencing the right directory? You need to set it in the notebook

Under the training folder , you should have s01 , s02 .. etc , and the pngs should be under each of those folders.

**Comment by reachablesa** [comment]
I changed the directory to the correct one in config class. That is why len(siamese_dataset) of is 400. As a solution I did the following change inside SiameseNetworkDataset;

        img0 = Image.open(Config.training_dir+img0_tuple[0])
        img1 = Image.open(Config.training_dir+img1_tuple[0]).

It solved the previous issue but created new ones:
 
in 
            img0 = self.transform(img0) of SiameseNetworkDataset

TypeError: unsupported operand type(s) for /: 'tuple' and 'int'.

**Comment by harveyslash** [comment]
Are you using python 3.6 ?

**Comment by reachablesa** [comment]
No, it is 2.7

**Comment by harveyslash** [comment]
This project requires3.6. 
Someone had this exact error , and it was solved by changing to python 3.6

**Comment by reachablesa** [comment]
Well I would like to use with 2.7 definetely. I will modify it to make it work in 2.7. I can update you if you like

**Comment by harveyslash** [comment]
Sure, ill create a 2.7 branch 
Also, your original issue could also be related to incorrect version.

**Comment by reachablesa** [comment]
Both issues are solved after updating torchvision from 0.1.7 to 0.1.9.
Thanks.
