### ISSUE TITLE
Can I debug the code using other IDE like pycharm instead of jupyter notebook?

### ISSUE THREAD

**Issue by wenston2006** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#13]
I am used to debug using pycharm and I found it hard to debug using jupyter notebook; for example if I want to step into some code, I use pdb; maybe I haven't found the tricks to debug using jupyter. So can I debug the code using pycharm?

**Comment by harveyslash** [comment]
You are free to debug the code in any way you like. jupypter has its own pdb that you can run. maybe this guide will help https://davidhamann.de/2017/04/22/debugging-jupyter-notebooks/
