### ISSUE TITLE
TypeError: mul received an invalid combination of arguments 

### ISSUE THREAD

**Issue by Nilay27** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#16]
while trying to train code, I encountered the following error: 

'''TypeError: mul received an invalid combination of arguments - got (Variable), but expected one of:
 * (float value)
      didn't match because some of the arguments have invalid types: (Variable)
 * (torch.FloatTensor other)
      didn't match because some of the arguments have invalid types: (Variable)'''

I'm a bit stuck at this point, I was just running the ipython implementation.

**Comment by Nilay27** [comment]
I encountered the error in the step 25 of ipython notebook, i.e 

'''for epoch in range(0,Config.train_number_epochs):
    for i, data in enumerate(train_dataloader,0):
        img0, img1 , label = data
        img0, img1 , label = img0.cuda(), img1.cuda() , label.cuda()
        optimizer.zero_grad()
        output1,output2 = net(img0,img1)
        loss_contrastive = criterion(output1,output2,label)
        loss_contrastive.backward()
        optimizer.step()
        if i %10 == 0 :
            print("Epoch number {}\n Current loss {}\n".format(epoch,loss_contrastive.item()))
            iteration_number +=10
            counter.append(iteration_number)
            loss_history.append(loss_contrastive.item())
show_plot(counter,loss_history)'''

**Comment by immortal3** [comment]
Are image in unit8 format ?

**Comment by tschoy** [comment]
Are you using torch 0.3.1? Torch 0.4.1 would be fine.
