### ISSUE TITLE
A question on custom dataset class

### ISSUE THREAD

**Issue by Jetyau** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#18]
Thanks for sharing your project. I just met a small question when reading your code. For

class SiameseNetworkDataset(Dataset):

    def __getitem__(self,index):
        img0_tuple = random.choice(self.imageFolderDataset.imgs)
        #we need to make sure approx 50% of images are in the same class
        should_get_same_class = random.randint(0,1) 
        if should_get_same_class:
            while True:
                #keep looping till the same class image is found
                img1_tuple = random.choice(self.imageFolderDataset.imgs) 
                if img0_tuple[1]==img1_tuple[1]:
                    break
        else:
            while True:
                #keep looping till a different class image is found
                
                img1_tuple = random.choice(self.imageFolderDataset.imgs) 
                if img0_tuple[1] !=img1_tuple[1]:
                    break
            img1_tuple = random.choice(self.imageFolderDataset.imgs)

when should_get_same_class equals to False, the coding keeps running until it finds img1_tuple that has different label as img0_tuple, but why do you use img1_tuple = random.choice(self.imageFolderDataset.imgs) again in last row?

Thank you very much.

**Comment by harveyslash** [comment]
This is a bug. Thanks for pointing it out. If you would like to fix it , I will accept the pull request
