### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by AnkitaBeniwal** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#19]
Hi,

I couldnt find the rquirements.txt in the github link you have provided
Kindly update it.

**Comment by neverUseThisName** [comment]
Me neither. Please supplement or remove the statement to erase misleading.

**Comment by stefann01** [comment]
Could not found the requirements.txt file...

**Comment by harveyslash** [comment]
Sorry about this. I am looking to spend more time in this project. I am also looking for contributors to make this a better documented project. please let me know if you are interested.
