### ISSUE TITLE
Could not find a version that satisfies the requirement ipython==6.1.0 (from -r requirements.txt (line 6)) 

### ISSUE THREAD

**Issue by NataliaDiaz** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#2]
pip install -r requirements.txt 
Collecting bleach==2.0.0 (from -r requirements.txt (line 1))
  Downloading bleach-2.0.0-py2.py3-none-any.whl
Collecting decorator==4.1.1 (from -r requirements.txt (line 2))
  Using cached decorator-4.1.1-py2.py3-none-any.whl
Collecting entrypoints==0.2.3 (from -r requirements.txt (line 3))
  Using cached entrypoints-0.2.3-py2.py3-none-any.whl
Collecting html5lib==0.999999999 (from -r requirements.txt (line 4))
  Using cached html5lib-0.999999999-py2.py3-none-any.whl
Collecting ipykernel==4.6.1 (from -r requirements.txt (line 5))
  Using cached ipykernel-4.6.1-py2-none-any.whl
Collecting ipython==6.1.0 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement ipython==6.1.0 (from -r requirements.txt (line 6)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0)
No matching distribution found for ipython==6.1.0 (from -r requirements.txt (line 6))

**Comment by harveyslash** [comment]
It looks like your pip isn't upgraded.

**Comment by NataliaDiaz** [comment]
I get the same also after updating pip with
sudo -H pip2 install --upgrade pip
also in Mac OS sierra

**Comment by harveyslash** [comment]
This requires python3.6 (so you'll have to use pip3.6).  Also , there's no cuda support for Mac , so you'll have to make changes to the code (remove all .cuda()) calls
