### ISSUE TITLE
Why you didn't use the "index" in __getitem__ function?

### ISSUE THREAD

**Issue by marsggbo** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#23]
It seems that you didn't use the variable — index in the __getitem__ function of SiameseNetworkDataset. So are all data traversed？

**Comment by trungnt11** [comment]
yes, have any fix bug any? @marsggbo

**Comment by harveyslash** [comment]
index was not used because for such a dataset, there is no well defined thing called index. We select images randomly based on a probability score (whether to pick the same class or not)
