### ISSUE TITLE
Convert images from grayscale to RGB

### ISSUE THREAD

**Issue by aks5bx** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#33]
Hi - I love what you have done here. I am currently trying to use this to incorporate colorized pictures. I keep uploading colorized pictures into the dataset, but it returns a greyscale version. Where do you convert the photos into grayscale (can't find it in the code)?

**Comment by aks5bx** [comment]
Fixed the issue when I changed all input photos (training and testing) to colorized.

**Comment by sramakrishnan247** [comment]
@aks5bx @harveyslash 
Where exactly does this happen? Even I'm using colorized images. Can you tell me what changes need to be made?
