### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

### ISSUE THREAD

**Issue by spencergoff** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#6]
Hi,
I downloaded this repo and I think the only modification I made to the code was to change the first line in In [15] from `net = SiameseNetwork().cuda()` to `net = SiameseNetwork()#.cuda()`. I made this change because I don't have a dedicated Nvidia GPU on my laptop. 

I'm getting the error 

> TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

triggered by this line: `for i, data in enumerate(train_dataloader,0):`

I haven't been able to figure out a solution. Any help is much appreciated.

**Comment by harveyslash** [comment]
This is a common error that is caused by a torch vision version mismatch. Make sure you are using python3.6 with torch vision `torchvision==0.1.8`

**Comment by spencergoff** [comment]
Thanks for your quick reply! 

> $ python -V
Python 3.6.3 :: Anaconda custom (64-bit)

So my Python version looks correct. 

How exactly do I check the torch vision version? I have a file on my computer called torchvision-0.1.8.dist-info, does this mean I have it?

**Comment by spencergoff** [comment]
I ran this command, no change. 
`conda install pytorch torchvision -c pytorch`

I also tried updating conda.

**Comment by harveyslash** [comment]
I don't really use conda so I don't know how to check version. But you can import into python and do `torchvison.__version__`

**Comment by spencergoff** [comment]
In the Jupyter Notebook? I tried `print(torchvison__version__)`

But it gives me the error: name 

> 'torchvison__version__' is not defined

Should I import something else besides what's already in your code?

**Comment by harveyslash** [comment]
sorry, i missed the . between torchvision and __version. 

I have updated the last comment.

**Comment by spencergoff** [comment]
Now with this in a cell of my Jupyter Notebook:
`torchvison.__version__`
I get:

> NameError: name 'torchvison' is not defined

Which is weird since I have `import torchvision` at the top of the notebook...
I also tried restarting the kernel and running all cells, same result. 
My notebook can be found here: https://github.com/spencergoff/Facial-Similarity-with-Siamese-Networks-in-Pytorch/tree/spencersbranch

**Comment by spencergoff** [comment]
I still haven't been able to resolve 

> TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

=-(

I also asked the [question](https://stackoverflow.com/questions/48990830/typeerror-unsupported-operand-types-for-tuple-and-int) to the StackOverflow community. 

@harveyslash

**Comment by spencergoff** [comment]
Any ideas? I've been trying out a Keras implementation, but its super slow.

**Comment by harveyslash** [comment]
can you convert to pip and a virtual env ? 
maybe then I can help
