### ISSUE TITLE
implemtation with webcam?

### ISSUE THREAD

**Issue by rashmisgh** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#8]
hey your work is quite good and i tried implementing it and was gud to see it worked. i need some help regarding the test directory, i want to make this work for webcam, the test image should be taken from webcam and the similarity should be tested with the image take from the webcam. but i can't understand how to do that. plz help me to achieve it.

**Comment by harveyslash** [comment]
To test. 
First run the image of the real person through the model. 

Then run the image you want to check through the model. 

After that calculate the distance on both the features. Lower distance means more similarity.

**Comment by rashmisgh** [comment]
here i am sharing the screen short of the cell where i want to make changes. In the testing_dir i want to pass the image taken from webcam and it will be a single image not a directory. 
![capture1](https://user-images.githubusercontent.com/37609385/37696336-e3141838-2cfb-11e8-8c82-e1f921445519.JPG)

**Comment by harveyslash** [comment]
As I mentioned before , the way to test is the same , regardless of number of images. 
Usually you compare the outputs with a few different classes, and select the one that has the least distance. 
If you have just one image, you have to choose a threshold value. distance value below this will be same , and distance values above this will be dissimilar.
