### ISSUE TITLE
Comment describing y labels is flipped.

### ISSUE THREAD

**Issue by Choco31415** [harveyslash/Facial-Similarity-with-Siamese-Networks-in-Pytorch#9]
In the original notebook, it states:

"The top row and the bottom row of any column is one pair. The 0s and 1s correspond to the column of the image. 0 indiciates dissimilar, and 1 indicates similar."

However, this contradicts both the blogpost and the actual output:

<img width="89" alt="screen shot 2018-05-09 at 10 08 56 am" src="https://user-images.githubusercontent.com/10004227/39819270-041b7cf6-5371-11e8-93e8-a6ba45d717c4.png">

"The Siamese Network dataset generates a pair of images , along with their similarity label (0 if genuine, 1 if imposter)."

The PR that I'm about to submit fixes this.

**Comment by harveyslash** [comment]
Thanks for pointing that out!
